name: allwork
description: "A new Flutter project."
publish_to: "none"
version: 1.5.0+1.3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.6.6
  audioplayers: ^6.1.0
  scrollable_positioned_list: ^0.3.8
  marquee: ^2.3.0
  intl: ^0.20.1
  keep_screen_on: ^4.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.14.1
  flutter_expandable_fab: ^2.3.0
  connectivity_plus: ^6.1.0
  realm: 20.0.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.2
  linkable: ^3.0.2
  share_plus: ^10.1.3
  path_provider: ^2.1.5
  get_ip_address: ^0.0.7
  bottom_picker: ^2.9.0
  flutter_html: ^3.0.0-beta.2
  #flutter_local_notifications: ^17.0.1
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  firebase_auth: ^5.4.1
  sign_in_with_apple: ^6.1.4
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  day_picker: 2.3.0
  rxdart: ^0.28.0
  onesignal_flutter: ^5.3.0
  upgrader: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg_phone.png
    - assets/images/bg_tab.png
    - assets/images/bg_desktop.png
    - assets/icons/Dhuhr.png
    - assets/icons/Fajr.png
    - assets/icons/image_5.png
    - assets/icons/image_7.png
    - assets/icons/Maghrib.png
    - assets/icons/credit.png
    - assets/app_icon.png
    - assets/icons/google_login.png
    - assets/images/start_popup_image.jpeg
    - assets/images/default_popup.jfif
    - assets/images/azadar_media.png
    - assets/images/azadar_media_text.png
    - assets/icons/apple_login.png

  fonts:
    - family: Gopika
      fonts:
        - asset: assets/font/GopikaThreeBold_0.otf
          weight: 700

    - family: MUHAMMADI
      fonts:
        - asset: assets/font/MUHAMMADI_QURANIC.ttf

    - family: Baskervville-Regular
      fonts:
        - asset: assets/font/Baskervville-Regular.ttf
