name: allwork
description: "A new Flutter project."
publish_to: 'none'


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.6.6
  audioplayers: ^6.1.0
  scrollable_positioned_list: ^0.3.8
  marquee: ^2.3.0
  intl: ^0.19.0
  keep_screen_on: ^3.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.1
  flutter_expandable_fab: ^2.3.0
  connectivity_plus: ^6.1.0
  realm: 20.0.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/bg_phone.png
    - assets/images/bg_tab.png
    - assets/images/bg_desktop.png
    - assets/icons/Dhuhr.png
    - assets/icons/Fajr.png
    - assets/icons/image_5.png
    - assets/icons/image_7.png
    - assets/icons/Maghrib.png
    - assets/app_icon.png
